### ISSUE TITLE
CocoaPods could not find compatible versions for pod "TestFairy"

### ISSUE THREAD

**Issue by wswebcreation** [testfairy/react-native-testfairy#44]
**Issue:**
Installing `react-native-testfairy@latest` fails with a CocoaPods error during pods install.

**Example:**
You can find the code [here](https://github.com/saucelabs/my-demo-app-rn), just add the module and run the `pod install` 

> NOTE: Latest working version for the sample project is `2.54.0`, `2.55.0` results in this error 
> ```log
> [!] CocoaPods could not find compatible versions for pod "TestFairy":
>   In snapshot (Podfile.lock):
>     TestFairy (= 1.29.2)
> 
>   In Podfile:
>     React-TestFairy (from `../node_modules/react-native-testfairy`) was resolved to 2.55.0, which depends on
>       TestFairy (= 1.29.4)
> 
> Specs satisfying the `TestFairy (= 1.29.2), TestFairy (= 1.29.4)` dependency were found, but they required a higher > minimum deployment target.
> ```

## Steps to reproduce
1. Create a new clean project `npx react-native init TfDemo --template react-native-template-typescript`
2. cd into the demo folder with `cd TfDemo`
2. add `react-native-testfairy` with `yarn add react-native-testfairy`
3. install pods with `npx pod-install ios `

## Logs
```logs
> npx react-native init TfDemo --template react-native-template-typescript
npx: installed 637 in 34.018s
                                                          
               ######                ######               
             ###     ####        ####     ###             
            ##          ###    ###          ##            
            ##             ####             ##            
            ##             ####             ##            
            ##           ##    ##           ##            
            ##         ###      ###         ##            
             ##  ########################  ##             
          ######    ###            ###    ######          
      ###     ##    ##              ##    ##     ###      
   ###         ## ###      ####      ### ##         ###   
  ##           ####      ########      ####           ##  
 ##             ###     ##########     ###             ## 
  ##           ####      ########      ####           ##  
   ###         ## ###      ####      ### ##         ###   
      ###     ##    ##              ##    ##     ###      
          ######    ###            ###    ######          
             ##  ########################  ##             
            ##         ###      ###         ##            
            ##           ##    ##           ##            
            ##             ####             ##            
            ##             ####             ##            
            ##          ###    ###          ##            
             ###     ####        ####     ###             
               ######                ######               
                                                          

                  Welcome to React Native!                
                 Learn once, write anywhere               

✔ Downloading template
✔ Copying template
✔ Processing template
✔ Installing CocoaPods dependencies (this may take a few minutes)

  
  Run instructions for Android:
    • Have an Android emulator running (quickest way to get started), or a device connected.
    • cd "/Users/wimselles/Sauce/Git/sauce-apps/TfDemo" && npx react-native run-android
  
  Run instructions for iOS:
    • cd "/Users/wimselles/Sauce/Git/sauce-apps/TfDemo" && npx react-native run-ios
    - or -
    • Open TfDemo/ios/TfDemo.xcworkspace in Xcode or run "xed -b ios"
    • Hit the Run button
    
  Run instructions for macOS:
    • See https://aka.ms/ReactNativeGuideMacOS for the latest up-to-date instructions.
    
  
> cd TfDemo
> yarn add react-native-testfairy
warning ../../../../package.json: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "react-native > react-native-codegen > jscodeshift@0.11.0" has unmet peer dependency "@babel/preset-env@^7.1.6".
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 6 new dependencies.
info Direct dependencies
└─ react-native-testfairy@2.56.0
info All dependencies
├─ is-arguments@1.1.1
├─ is-generator-function@1.0.10
├─ is-typed-array@1.1.8
├─ react-native-testfairy@2.56.0
├─ util@0.12.4
└─ which-typed-array@1.1.7
> npx pod-install ios
npx: installed 1 in 2.079s
Scanning for pods...
1.10.1
> pod install
Auto-linking React Native module for target `TfDemo`: React-TestFairy
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "TestFairy":
  In Podfile:
    React-TestFairy (from `../node_modules/react-native-testfairy`) was resolved to 2.56.0, which depends on
      TestFairy (= 1.29.5)

None of your spec sources contain a spec satisfying the dependency: `TestFairy (= 1.29.5)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Aborting run
An unexpected error was encountered. Please report it as a bug:
CocoaPodsError: Command `pod install` failed.
└─ Cause: pod exited with non-zero code: 31
    at CocoaPodsPackageManager._installAsync (/Users/wimselles/.npm/_npx/4319/lib/node_modules/pod-install/build/index.js:2:92213)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async CocoaPodsPackageManager.installAsync (/Users/wimselles/.npm/_npx/4319/lib/node_modules/pod-install/build/index.js:2:90176)
    at async runAsync (/Users/wimselles/.npm/_npx/4319/lib/node_modules/pod-install/build/index.js:2:106198)
    at async /Users/wimselles/.npm/_npx/4319/lib/node_modules/pod-install/build/index.js:2:106284 {
  code: 'COMMAND_FAILED',
  cause: Error: pod exited with non-zero code: 31
      at ChildProcess.h (/Users/wimselles/.npm/_npx/4319/lib/node_modules/pod-install/build/index.js:2:1073)
      at Object.onceWrapper (events.js:520:26)
      at ChildProcess.emit (events.js:400:28)
      at maybeClose (internal/child_process.js:1058:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
      ...
      at Object.spawnAsync [as default] (/Users/wimselles/.npm/_npx/4319/lib/node_modules/pod-install/build/index.js:2:558)
      at CocoaPodsPackageManager._runAsync (/Users/wimselles/.npm/_npx/4319/lib/node_modules/pod-install/build/index.js:2:92995)
      at CocoaPodsPackageManager._installAsync (/Users/wimselles/.npm/_npx/4319/lib/node_modules/pod-install/build/index.js:2:90499)
      at CocoaPodsPackageManager.installAsync (/Users/wimselles/.npm/_npx/4319/lib/node_modules/pod-install/build/index.js:2:90187)
      at runAsync (/Users/wimselles/.npm/_npx/4319/lib/node_modules/pod-install/build/index.js:2:106206)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async /Users/wimselles/.npm/_npx/4319/lib/node_modules/pod-install/build/index.js:2:106284 {
    pid: 4334,
    output: [ '', '' ],
    stdout: '',
    stderr: '',
    status: 31,
    signal: null
  },
  isPackageManagerError: true
}
```

**Comment by wswebcreation** [comment]
Closing this one, `pod install --repo-update` worked 🤦
